apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aks-terraform-samples
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-premium-retain
  resources:
    requests:
      storage: 20Gi
