apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-db-init
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aks-terraform-samples
data:
  mysql_usermgmt.sql: |-
    CREATE DATABASE IF NOT EXISTS webappdb;
    USE webappdb;
