apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aks-terraform-samples
type: Opaque
stringData:
  mysql-root-password: dbpassword11
