apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp
  labels:
    app.kubernetes.io/name: usermgmt-webapp
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aks-terraform-samples
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: usermgmt-webapp
  ports:
    - name: http
      port: 80
      targetPort: http
