apiVersion: v1
kind: Service
metadata:
  name: windows-app1
  labels:
    app.kubernetes.io/name: windows-app1
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aks-terraform-samples
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: windows-app1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
