apiVersion: v1
kind: Service
metadata:
  name: nginx-web-loadbalancer
  labels:
    app.kubernetes.io/name: nginx-web
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aks-terraform-samples
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-web
  ports:
    - name: http
      port: 80
      targetPort: http
